apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "productservice"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
    spec:
      serviceAccountName: pubsub-sa
      containers:
      - name: product-service
        image: 660633971866.dkr.ecr.us-east-1.amazonaws.com/introspect1eks-product:latest
        ports:
        - containerPort: 8080
      - name: daprd
        image: daprio/daprd:1.13.5
        ports:
        - containerPort: 3500
          name: dapr-http
        - containerPort: 50001
          name: dapr-grpc
        - containerPort: 9090
          name: dapr-metrics
        args:
        - --dapr-http-port
        - "3500"
        - --dapr-grpc-port
        - "50001"
        - --dapr-metrics-port
        - "9090"
        - --app-id
        - productservice
        - --app-port
        - "8080"
        - --enable-api-logging
        - "true"
        - --log-level
        - info
        - --app-protocol
        - http
        - --placement-hostname
        - dapr-placement-server.dapr-system.svc.cluster.local:50005
        - --sentry-address
        - dapr-sentry.dapr-system.svc.cluster.local:443
        - --control-plane-address
        - dapr-sidecar-injector.dapr-system.svc.cluster.local:4000
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        - name: DAPR_METRICS_PORT
          value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: product-service
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer